/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author prelius
 */
public class Login_frame extends javax.swing.JFrame {

    /**
     * Creates new form Login_frame
     */
    Window window;
    public Login_frame(Window win, Connection c) {
        initComponents();
        window = win;
        con = c;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginField = new javax.swing.JTextField();
        PassField = new javax.swing.JPasswordField();
        LogButton = new javax.swing.JButton();
        RegButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GuestButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        LoginField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LoginField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        PassField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PassField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });
        PassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassFieldKeyPressed(evt);
            }
        });

        LogButton.setText("Prihlásiť");
        LogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogButtonActionPerformed(evt);
            }
        });

        RegButton.setText("Registrovať");
        RegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prihlasovacie meno");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Heslo");

        GuestButton.setText("Pokračovať ako hosť");
        GuestButton.setEnabled(false);
        GuestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoginField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(PassField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GuestButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegButton)
                .addGap(18, 18, 18)
                .addComponent(GuestButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogButtonActionPerformed
        // TODO add your handling code here:
        if((!LoginField.getText().isEmpty()) && 
                (PassField.getPassword().length > 0))
        {
            
            try {
                Statement stm = con.createStatement();
                String sql = "SELECT * FROM \"public\".\"users\" WHERE name like '"+ LoginField.getText() +"';";
                ResultSet rs = stm.executeQuery(sql);
                if(rs.next()) {
                    String pss = Arrays.toString(PassField.getPassword());
                    if(rs.getString("pass").equals(Arrays.toString(PassField.getPassword()))) {
                        System.out.println("Prihlásený ako " + rs.getString("name"));
                        window.setName(LoginField.getText());
                        window.setEnabled(true);
                        window.setVisible(true);
                        
                        if(rs.getString("name").equals("admin")){
                            window.enableAdmin();
                        }
                        
                        this.setEnabled(false);
                        this.setVisible(false);
                    }
                    else {
                        //System.out.println("Zadali ste zle heslo");
                        JOptionPane.showMessageDialog(this, "Zadali ste zle heslo!", "Chyba prihlasenia", JOptionPane.WARNING_MESSAGE);
                    }
                }
                else
                    //System.out.println("Pouzivatel neexistuje");
                    JOptionPane.showMessageDialog(this, "Pouzivatel neexistuje!", "Chyba prihlasenia", JOptionPane.WARNING_MESSAGE);
                stm.close();
                con.commit();
            } catch (SQLException ex) {
                Logger.getLogger(Login_frame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else {
            System.out.println("Nezadali ste meno alebo heslo");
            JOptionPane.showMessageDialog(this, "Nezadali ste meno alebo heslo", "Chyba prihlasenia", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_LogButtonActionPerformed

    private void GuestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestButtonActionPerformed
        // TODO add your handling code here:
        //window.user = "Host";
        window.setName("Host");
        window.setEnabled(true);
        window.setVisible(true);
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_GuestButtonActionPerformed

    private void RegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegButtonActionPerformed
        try {
            // TODO add your handling code here:
            Statement stm = con.createStatement();
            String sql = "INSERT INTO \"public\".\"users\" (name, pass, type)"
                    + " VALUES ('" + LoginField.getText()  + "', '"
                    + Arrays.toString(PassField.getPassword()) + "', 1);";
            stm.executeUpdate(sql);
            stm.close();
            con.commit();
        } catch (SQLException ex) {
            Logger.getLogger(Login_frame.class.getName()).log(Level.SEVERE, null, ex);
            try {
                con.rollback();
            } catch (SQLException ex1) {
                Logger.getLogger(Login_frame.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
        
    }//GEN-LAST:event_RegButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            con.close();
            System.out.println("Ukoncenie databazy");
        } catch (SQLException ex) {
            Logger.getLogger(Login_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void PassFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldKeyPressed

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
        LogButton.doClick();
    }//GEN-LAST:event_PassFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    Connection con;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuestButton;
    private javax.swing.JButton LogButton;
    private javax.swing.JTextField LoginField;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JButton RegButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
